name: lab3-spark

services:
  # --- NODO 1: SPARK MASTER ---
  spark-master:
    build: .
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"   # Spark UI
      - "7077:7077"   # Spark Master
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks

  # --- NODO 2: SPARK WORKER ---
  spark-worker:
    build: .
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks

  # --- NODO 3: JUPYTER LAB ---
  jupyter-lab:
    build: .
    container_name: jupyter-lab
    ports:
      - "8888:8888"   # Jupyter
      - "4040:4040"   # Spark Jobs UI
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks

